language: python

sudo: false

env:
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin
  - eval `luarocks path --bin`
  - lua -v

install:
  - luarocks make

script:
  - lua test.lua
