language: python

sudo: false

env:
  matrix:
    - LUA=lua V=5.1
    - LUA=lua V=5.2
    - LUA=lua V=5.3
    - LUA=luajit V=2.0
    - LUA=luajit V=2.1

before_install:
  - pip install hererocks
  - hererocks here -r^ --$LUA $V
  - export PATH=$PATH:$PWD/here/bin
  - eval `luarocks path --bin`

install:
  - luarocks make

script:
  - $LUA test.lua
