name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        lua:
          - "lua 5.1"
          - "lua 5.2"
          - "lua 5.3"
          - "lua 5.4"
          - "luajit 2.0"
          - "luajit 2.1"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dependencies
        run: |-
          sudo apt install libgdbm-dev
      - name: Hererocks
        run: |-
          pip install hererocks
          hererocks env --${{ matrix.lua }} -rlatest
      - name: Build
        run: |-
          source ./env/bin/activate
          luarocks make
      - name: Test
        run: |-
          source ./env/bin/activate
          lua test.lua
